#ifndef _DISPLAY_CONFIGURATION_H_
#define _DISPLAY_CONFIGURATION_H_

#define FONT_WIDTH         5
#define FONT_HEIGHT        7
#define FONT_MARGIN_RIGHT  1
#define FONT_MARGIN_BOTTOM 1
#define SCREEN_WIDTH       96
#define SCREEN_HEIGHT      96

#define FONT_WIDTH_WITH_MARGIN  (FONT_WIDTH + FONT_MARGIN_RIGHT)
#define FONT_HEIGHT_WITH_MARGIN (FONT_HEIGHT + FONT_MARGIN_BOTTOM)

#define HEADER_PANEL_HEIGHT     (FONT_HEIGHT_WITH_MARGIN + 1)
#define MENU_PANEL_HEIGHT       (FONT_HEIGHT_WITH_MARGIN + 1)

#define MAX_CHARACTERS_PER_LINE (SCREEN_WIDTH / FONT_WIDTH_WITH_MARGIN)

#endif
